### PR TITLE
Change attribute names to be unique.

### PR DESCRIPTION
**Pull request by DHosseiny**
attribute names will be have conflicts if not unique.

### CODE REVIEW

**Comment by wasabeef** [comment]
@DHosseiny 
Could you check the CLA?

**Comment by DHosseiny** [comment]
@wasabeef I signed but it says: 
seyyed davud hosseiny seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
what I can do?

**Comment by wasabeef** [comment]
@DHosseiny 
Did you this? 
https://cla-assistant.io/cats-oss/android-gpuimage

Login with Github account

**Comment by DHosseiny** [comment]
Yes. this is accepted.

**Comment by wasabeef** [comment]
@DHosseiny
I see, Thanks.

**Pull request merged**
